interface SummaryData {
  title: string | null;
  summary: string | null;
  key_points: string[] | null;
  action_items: string[] | null;
  topics: string[] | null;
  sentiment: string | null;
  model_used: string;
}

interface SummaryPanelProps {
  summary: SummaryData;
}

const sentimentColors: Record<string, { bg: string; text: string }> = {
  positive: { bg: "rgba(34,197,94,0.15)", text: "#22c55e" },
  negative: { bg: "rgba(239,68,68,0.15)", text: "#ef4444" },
  neutral: { bg: "rgba(156,163,175,0.15)", text: "#9ca3af" },
  informative: { bg: "rgba(59,130,246,0.15)", text: "#3b82f6" },
  tutorial: { bg: "rgba(168,85,247,0.15)", text: "#a855f7" },
  discussion: { bg: "rgba(234,179,8,0.15)", text: "#eab308" },
};

export function SummaryPanel({ summary }: SummaryPanelProps) {
  const sentimentStyle = sentimentColors[summary.sentiment ?? "neutral"] ?? sentimentColors.neutral;

  return (
    <div className="space-y-5 overflow-y-auto px-3 py-3">
      {/* Summary text */}
      {summary.summary && (
        <div>
          <h3
            className="mb-2 text-xs font-semibold uppercase tracking-wider"
            style={{ color: "var(--color-text-secondary)" }}
          >
            Summary
          </h3>
          <p className="text-sm leading-relaxed" style={{ color: "var(--color-text)" }}>
            {summary.summary}
          </p>
        </div>
      )}

      {/* Key Points */}
      {summary.key_points && summary.key_points.length > 0 && (
        <div>
          <h3
            className="mb-2 text-xs font-semibold uppercase tracking-wider"
            style={{ color: "var(--color-text-secondary)" }}
          >
            Key Points
          </h3>
          <ul className="space-y-1.5">
            {summary.key_points.map((point, i) => (
              <li key={i} className="flex gap-2 text-sm" style={{ color: "var(--color-text)" }}>
                <span style={{ color: "var(--color-primary)" }}>&#8226;</span>
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Action Items */}
      {summary.action_items && summary.action_items.length > 0 && (
        <div>
          <h3
            className="mb-2 text-xs font-semibold uppercase tracking-wider"
            style={{ color: "var(--color-text-secondary)" }}
          >
            Action Items
          </h3>
          <ul className="space-y-1.5">
            {summary.action_items.map((item, i) => (
              <li key={i} className="flex gap-2 text-sm" style={{ color: "var(--color-text)" }}>
                <span style={{ color: "#22c55e" }}>&#9745;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Topics + Sentiment */}
      <div className="flex flex-wrap items-center gap-2">
        {summary.topics?.map((topic, i) => (
          <span
            key={i}
            className="rounded-full px-2.5 py-0.5 text-xs"
            style={{
              backgroundColor: "rgba(99,102,241,0.15)",
              color: "var(--color-primary)",
            }}
          >
            {topic}
          </span>
        ))}
        {summary.sentiment && (
          <span
            className="rounded-full px-2.5 py-0.5 text-xs capitalize"
            style={{
              backgroundColor: sentimentStyle.bg,
              color: sentimentStyle.text,
            }}
          >
            {summary.sentiment}
          </span>
        )}
      </div>

      {/* Model info */}
      <p className="text-xs" style={{ color: "var(--color-text-secondary)" }}>
        Generated by {summary.model_used}
      </p>
    </div>
  );
}
